---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.ports.containerPort }}
      targetPort: {{ .Values.ports.containerPort }}
  selector:
    app: {{ .Release.Name }}
